"""Manifest audit + human-readable documentation generation.

Compares ``manifest.json`` (the declared routing table) against the physical
``variants/`` tree and regenerates ``manifest.md``. This is specific to the
Skyrim/variants repo layout; the build pipeline only runs it for profile types
that opt into it.
"""
import json
from pathlib import Path
from collections import defaultdict

# ==============================================================================
# Core Logic Functions
# ==============================================================================

def load_manifest(manifest_path):
    """Loads the JSON routing table of variant files."""
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def scan_variants(variants_dir):
    """Crawls the physical file system to map actual variant implementations."""
    implementations = defaultdict(list)
    if not variants_dir.exists():
        return implementations

    for variant_file in variants_dir.glob("**/*.txt"):
        relative_path = variant_file.relative_to(variants_dir)
        variant_name = relative_path.parts[0]
        implementations[variant_file.name].append(variant_name)
    return implementations

def scan_core(core_dir):
    """Gathers a list of all universal scripts currently in the core directory."""
    if not core_dir.exists():
        return []
    return sorted([f.name for f in core_dir.glob("*.txt")])

def audit_repository(manifest_data, scanned_data):
    """Compares the JSON manifest against the physical variants file system."""

    audit_lines = ["Auditing repository health...\n"]
    ghosts = 0
    undocumented = 0

    # Check for Ghost Entries
    for script, declared_variants in manifest_data.items():
        actual_variants = scanned_data.get(script, [])
        missing = set(declared_variants) - set(actual_variants)
        if missing:
            audit_lines.append(f"  [!] GHOST ENTRY: '{script}' is declared for {list(missing)}, but the file is missing.")
            ghosts += 1

    # Check for Undocumented Files
    for script, actual_variants in scanned_data.items():
        declared_variants = manifest_data.get(script, [])
        untracked = set(actual_variants) - set(declared_variants)
        if untracked:
            audit_lines.append(f"  [!] UNDOCUMENTED: '{script}' physically exists in {list(untracked)} but is not in manifest.json.")
            undocumented += 1

    # Append the final status
    if ghosts == 0 and undocumented == 0:
        audit_lines.append("  [+] Health Check Passed: manifest.json perfectly matches the physical variants folder.")
    else:
        audit_lines.append(f"\n  -> [!] Audit finished with {ghosts} ghost(s) and {undocumented} undocumented variant file(s).")

    # Print the entire audit report atomically
    print("\n".join(audit_lines))

def generate_markdown(manifest_data, core_scripts, md_path):
    """Compiles the JSON data and Core scans into a human-readable Markdown document."""
    lines = [
        "# Repository Manifest\n",
        "> *Auto-generated by `symlink-audit`. Do not edit this file directly.*",
        "> *To update the variants list, edit `manifest.json`. Core scripts are auto-discovered.*\n",

        "## Universal Core Scripts",
        "These scripts are deployed to all configurations automatically.\n"
    ]

    if core_scripts:
        for script in core_scripts:
            lines.append(f"* `{script}`")
    else:
        lines.append("* *No core scripts found.*")

    lines.extend([
        "\n## Variant-Specific Scripts",
        "These scripts are routed only to the specified modlists.\n",
        "| Script Name | Active Variants |",
        "| :--- | :--- |"
    ])

    for script, variants in sorted(manifest_data.items()):
        variant_str = ", ".join(f"`{v}`" for v in sorted(variants))
        lines.append(f"| `{script}` | {variant_str} |")

    with open(md_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")

# ==============================================================================
# Execution Orchestration
# ==============================================================================

def run_maintenance(base_dir=None):
    base_dir = base_dir or Path.cwd()

    manifest_json_path = base_dir / "manifest.json"
    manifest_md_path = base_dir / "manifest.md"
    variants_dir = base_dir / "variants"
    core_dir = base_dir / "core"

    if not manifest_json_path.exists():
        print(f"  [*] No manifest.json at {manifest_json_path} - nothing to audit.")
        return

    # Load Data
    manifest_data = load_manifest(manifest_json_path)
    scanned_variants = scan_variants(variants_dir)
    core_scripts = scan_core(core_dir)

    # Audit Variants
    audit_repository(manifest_data, scanned_variants)

    # Generate Unified Documentation
    generate_markdown(manifest_data, core_scripts, manifest_md_path)
    print(f"\n  [+] Generated human-readable manifest at: {manifest_md_path.name}")
